# Generated by Django 5.2 on 2025-05-13 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('expiration_date', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
