services:
  redis:
    container_name: pethsop_redis
    image: docker.arvancloud.ir/redis:7.4.1
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - main_network

  petshop:
    container_name: petshop
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    image: petshop:1.0.0
    volumes:
      - petshop_data:/PetShop
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - main_network
    depends_on:
      - redis

  celery:
    container_name: celery_worker
    image: petshop:1.0.0
    entrypoint: celery -A config worker -l INFO
    volumes:
      - petshop_data:/PetShop
    env_file:
      - .env
    depends_on:
      - redis
      - petshop
    restart: always
    networks:
      - main_network
    environment:
      - C_FORCE_ROOT="true"

volumes:
  petshop_data:
  redis_data:

networks:
  main_network:
    driver: bridge