# Generated by Django 5.2 on 2025-05-06 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('unit_price', models.DecimalField(db_index=True, decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(10000)])),
                ('discount_percent', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('final_price', models.DecimalField(db_index=True, decimal_places=0, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(10000)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
