# Generated by Django 5.2 on 2025-05-04 19:03

import petshop.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[petshop.users.validators.validate_iranian_phone_number], verbose_name='phone number'),
        ),
    ]
