# Generated by Django 5.2 on 2025-05-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created_date',), 'verbose_name_plural': 'Addreses'},
        ),
    ]
