# Generated by Django 5.2 on 2025-05-15 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=230, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
            options={
                'ordering': ('-updated_date',),
            },
        ),
    ]
