# Generated by Django 5.2 on 2025-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-title',),
            },
        ),
    ]
