# Generated by Django 5.2 on 2025-05-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-updated_date',)},
        ),
    ]
