# Generated by Django 5.2 on 2025-05-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articlereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlereview',
            name='rate',
        ),
    ]
